### PR TITLE
Add schema file

### PR DESCRIPTION
**Pull request by AntonMiJu**
add general view of tables for database

### CODE REVIEW

**Comment by AntonMiJu** [comment]
@Himynameismarco waiting for your feedback here. What else columns do we need?

**Review by Himynameismarco — COMMENTED** [review]
Marco Zander, [20. Jan 2023 at 22:19:38]:
Journals should be the table (is this the right term) for everything that is written or just for a certain category/ for a certain mode? If for everything, we will need a column for mode and/or submode. Maybe we should save the language it belongs to, too?

I am not sure what’s the best way to represent mode and sub-mode though.

**Comment by Himynameismarco** [comment]
The last thing, I’d say is: If this will be our table for everything we store, we might consider calling it “TEXTS” instead of “JOURNALS”, because later there will not only be journal entries but more creative writing saved in this table, too.

**Review by Himynameismarco — APPROVED** [review]
See discussion on Telegram for potential future improvements.

**Pull request merged**
